version: '3.2'
services:
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/MYSQL_DATABASE
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: root
    ports:
      - 3305:3306